// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryvtyjiayqaqbbffrwgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5dnR5amlheXFhcWJiZmZyd2dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MzM5NDEsImV4cCI6MjA2OTUwOTk0MX0.K7Cjs9FWM8bZRdC7qMdBj3LPQFE0bzfsnEwkolacO0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});